/*
 * osu! Collector
 * Upload and get osu collections
 *
 * OpenAPI spec version: 1.0.0
 * Contact: junarvi@yahoo.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OsuCollector);
  }
}(this, function(expect, OsuCollector) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LikeData', function() {
      beforeEach(function() {
        instance = new OsuCollector.LikeData();
      });

      it('should create an instance of LikeData', function() {
        // TODO: update the code to test LikeData
        expect(instance).to.be.a(OsuCollector.LikeData);
      });

      it('should have the property osuUserId (base name: "osuUserId")', function() {
        // TODO: update the code to test the property osuUserId
        expect(instance).to.have.property('osuUserId');
        // expect(instance.osuUserId).to.be(expectedValueLiteral);
      });

      it('should have the property like (base name: "like")', function() {
        // TODO: update the code to test the property like
        expect(instance).to.have.property('like');
        // expect(instance.like).to.be(expectedValueLiteral);
      });

    });
  });

}));
