/*
 * osu! Collector
 * Upload and get osu collections
 *
 * OpenAPI spec version: 1.0.0
 * Contact: junarvi@yahoo.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CommentData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CommentData'));
  } else {
    // Browser globals (root is window)
    if (!root.OsuCollector) {
      root.OsuCollector = {};
    }
    root.OsuCollector.CollectionData = factory(root.OsuCollector.ApiClient, root.OsuCollector.CommentData);
  }
}(this, function(ApiClient, CommentData) {
  'use strict';

  /**
   * The CollectionData model module.
   * @module model/CollectionData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CollectionData</code>.
   * @alias module:model/CollectionData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CollectionData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CollectionData} obj Optional instance to populate.
   * @return {module:model/CollectionData} The populated <code>CollectionData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('uploader'))
        obj.uploader = ApiClient.convertToType(data['uploader'], 'String');
      if (data.hasOwnProperty('uploaderId'))
        obj.uploaderId = ApiClient.convertToType(data['uploaderId'], 'Number');
      if (data.hasOwnProperty('likes'))
        obj.likes = ApiClient.convertToType(data['likes'], 'Number');
      if (data.hasOwnProperty('comments'))
        obj.comments = ApiClient.convertToType(data['comments'], [CommentData]);
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} uploader
   */
  exports.prototype.uploader = undefined;

  /**
   * @member {Number} uploaderId
   */
  exports.prototype.uploaderId = undefined;

  /**
   * @member {Number} likes
   */
  exports.prototype.likes = undefined;

  /**
   * @member {Array.<module:model/CommentData>} comments
   */
  exports.prototype.comments = undefined;


  return exports;

}));
