/*
 * osu! Collector
 * Upload and get osu collections
 *
 * OpenAPI spec version: 1.0.0
 * Contact: junarvi@yahoo.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OsuCollector) {
      root.OsuCollector = {};
    }
    root.OsuCollector.CollectionUploadData = factory(root.OsuCollector.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CollectionUploadData model module.
   * @module model/CollectionUploadData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CollectionUploadData</code>.
   * @alias module:model/CollectionUploadData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CollectionUploadData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CollectionUploadData} obj Optional instance to populate.
   * @return {module:model/CollectionUploadData} The populated <code>CollectionUploadData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('beatmaps'))
        obj.beatmaps = ApiClient.convertToType(data['beatmaps'], [Object]);
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {Array.<Object>} beatmaps
   */
  exports.prototype.beatmaps = undefined;


  return exports;

}));
