/*
 * osu! Collector
 * Upload and get osu collections
 *
 * OpenAPI spec version: 1.0.0
 * Contact: junarvi@yahoo.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CollectionUploadData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CollectionUploadData'));
  } else {
    // Browser globals (root is window)
    if (!root.OsuCollector) {
      root.OsuCollector = {};
    }
    root.OsuCollector.CollectionsUploadData = factory(root.OsuCollector.ApiClient, root.OsuCollector.CollectionUploadData);
  }
}(this, function(ApiClient, CollectionUploadData) {
  'use strict';

  /**
   * The CollectionsUploadData model module.
   * @module model/CollectionsUploadData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CollectionsUploadData</code>.
   * @alias module:model/CollectionsUploadData
   * @class
   * @param uploader {String} 
   */
  var exports = function(uploader) {
    this.uploader = uploader;
  };

  /**
   * Constructs a <code>CollectionsUploadData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CollectionsUploadData} obj Optional instance to populate.
   * @return {module:model/CollectionsUploadData} The populated <code>CollectionsUploadData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('uploader'))
        obj.uploader = ApiClient.convertToType(data['uploader'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('uploaderId'))
        obj.uploaderId = ApiClient.convertToType(data['uploaderId'], 'Number');
      if (data.hasOwnProperty('collections'))
        obj.collections = ApiClient.convertToType(data['collections'], [CollectionUploadData]);
    }
    return obj;
  }

  /**
   * @member {String} uploader
   */
  exports.prototype.uploader = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {Number} uploaderId
   */
  exports.prototype.uploaderId = undefined;

  /**
   * @member {Array.<module:model/CollectionUploadData>} collections
   */
  exports.prototype.collections = undefined;


  return exports;

}));
