/*
 * osu! Collector
 * Upload and get osu collections
 *
 * OpenAPI spec version: 1.0.0
 * Contact: junarvi@yahoo.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OsuCollector) {
      root.OsuCollector = {};
    }
    root.OsuCollector.CommentData = factory(root.OsuCollector.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CommentData model module.
   * @module model/CommentData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CommentData</code>.
   * @alias module:model/CommentData
   * @class
   * @param username {Number} 
   * @param userId {Number} osu user id. osuUserId 0 is reserved for guests
   * @param comment {String} 
   */
  var exports = function(username, userId, comment) {
    this.username = username;
    this.userId = userId;
    this.comment = comment;
  };

  /**
   * Constructs a <code>CommentData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CommentData} obj Optional instance to populate.
   * @return {module:model/CommentData} The populated <code>CommentData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'Number');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('comment'))
        obj.comment = ApiClient.convertToType(data['comment'], 'String');
      if (data.hasOwnProperty('datePosted'))
        obj.datePosted = ApiClient.convertToType(data['datePosted'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} username
   */
  exports.prototype.username = undefined;

  /**
   * osu user id. osuUserId 0 is reserved for guests
   * @member {Number} userId
   */
  exports.prototype.userId = undefined;

  /**
   * @member {String} comment
   */
  exports.prototype.comment = undefined;

  /**
   * @member {String} datePosted
   */
  exports.prototype.datePosted = undefined;


  return exports;

}));
