/*
 * osu! Collector
 * Upload and get osu collections
 *
 * OpenAPI spec version: 1.0.0
 * Contact: junarvi@yahoo.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OsuCollector) {
      root.OsuCollector = {};
    }
    root.OsuCollector.LikeData = factory(root.OsuCollector.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The LikeData model module.
   * @module model/LikeData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>LikeData</code>.
   * @alias module:model/LikeData
   * @class
   * @param osuUserId {Number} osuUserId 0 is reserved for guests
   * @param like {Boolean} 
   */
  var exports = function(osuUserId, like) {
    this.osuUserId = osuUserId;
    this.like = like;
  };

  /**
   * Constructs a <code>LikeData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LikeData} obj Optional instance to populate.
   * @return {module:model/LikeData} The populated <code>LikeData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('osuUserId'))
        obj.osuUserId = ApiClient.convertToType(data['osuUserId'], 'Number');
      if (data.hasOwnProperty('like'))
        obj.like = ApiClient.convertToType(data['like'], 'Boolean');
    }
    return obj;
  }

  /**
   * osuUserId 0 is reserved for guests
   * @member {Number} osuUserId
   */
  exports.prototype.osuUserId = undefined;

  /**
   * @member {Boolean} like
   */
  exports.prototype.like = undefined;


  return exports;

}));
