/*
 * osu! Collector
 * Upload and get osu collections
 *
 * OpenAPI spec version: 1.0.0
 * Contact: junarvi@yahoo.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OsuCollector) {
      root.OsuCollector = {};
    }
    root.OsuCollector.RangeParametersWithDate = factory(root.OsuCollector.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The RangeParametersWithDate model module.
   * @module model/RangeParametersWithDate
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RangeParametersWithDate</code>.
   * @alias module:model/RangeParametersWithDate
   * @class
   * @param dateRange {String} 
   * @param startFrom {Number} 
   * @param count {Number} 
   */
  var exports = function(dateRange, startFrom, count) {
    this.dateRange = dateRange;
    this.startFrom = startFrom;
    this.count = count;
  };

  /**
   * Constructs a <code>RangeParametersWithDate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RangeParametersWithDate} obj Optional instance to populate.
   * @return {module:model/RangeParametersWithDate} The populated <code>RangeParametersWithDate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('dateRange'))
        obj.dateRange = ApiClient.convertToType(data['dateRange'], 'String');
      if (data.hasOwnProperty('startFrom'))
        obj.startFrom = ApiClient.convertToType(data['startFrom'], 'Number');
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} dateRange
   */
  exports.prototype.dateRange = undefined;

  /**
   * @member {Number} startFrom
   */
  exports.prototype.startFrom = undefined;

  /**
   * @member {Number} count
   */
  exports.prototype.count = undefined;


  return exports;

}));
